name: CMake

on:
  # push:
  #   branches: [ master ]
  # pull_request:
  #   branches: [ master ]
  # schedule:
  #   - cron: 0 16 * * * # run at 1 AM JST
  workflow_dispatch:

permissions:
  contents: read

defaults:
  run:
    shell: bash
    working-directory: ./cpp

env:
  BUILD_TYPE: Release

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1
        submodules: recursive

    - name: Configure CMake
      run: cmake -B ./build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ./build --config ${{env.BUILD_TYPE}}

    - name: Test
      run: |
        cd ./build
        ctest -C ${{env.BUILD_TYPE}}
